CREATE OR REPLACE VIEW public.pbx_softphone_users_safe
WITH (security_invoker = on) AS
SELECT
  id,
  organization_id,
  client_id,
  portal_user_id,
  extension_id,
  extension,
  sip_domain,
  display_name,
  status,
  last_seen_at,
  created_at,
  updated_at,
  forward_enabled,
  forward_to,
  dnd_enabled,
  wss_url,
  device_type,
  last_seen_ios,
  last_seen_android,
  last_seen_mac,
  last_seen_windows,
  last_seen_linux,
  last_seen_web,
  active_platforms,
  total_calls,
  account_status,
  custom_status,
  status_emoji,
  out_of_office_until,
  cc_role,
  cc_queues,
  cc_status,
  cc_pause_reason,
  cc_calls_today,
  cc_avg_handle_time,
  cc_logged_in_at,
  cc_skills,
  app_access_enabled,
  desktop_access_enabled,
  mobile_access_enabled,
  source,
  pbx_uuid,
  domain_uuid,
  last_pbx_seen_at,
  sync_status,
  is_demo
FROM public.pbx_softphone_users;

GRANT SELECT (
  id,
  organization_id,
  client_id,
  portal_user_id,
  extension_id,
  extension,
  sip_domain,
  display_name,
  status,
  last_seen_at,
  created_at,
  updated_at,
  forward_enabled,
  forward_to,
  dnd_enabled,
  wss_url,
  device_type,
  last_seen_ios,
  last_seen_android,
  last_seen_mac,
  last_seen_windows,
  last_seen_linux,
  last_seen_web,
  active_platforms,
  total_calls,
  account_status,
  custom_status,
  status_emoji,
  out_of_office_until,
  cc_role,
  cc_queues,
  cc_status,
  cc_pause_reason,
  cc_calls_today,
  cc_avg_handle_time,
  cc_logged_in_at,
  cc_skills,
  app_access_enabled,
  desktop_access_enabled,
  mobile_access_enabled,
  source,
  pbx_uuid,
  domain_uuid,
  last_pbx_seen_at,
  sync_status,
  is_demo
) ON public.pbx_softphone_users TO authenticated;

REVOKE SELECT (sip_password) ON public.pbx_softphone_users FROM authenticated, anon;
GRANT SELECT ON public.pbx_softphone_users_safe TO authenticated;
GRANT SELECT ON public.pbx_softphone_users_safe TO service_role;